apiVersion: v1
kind: Service
metadata:
  name: es-monitor-api
  annotations:
    {{ .Values.prometheusDomain }}/scrape: "true"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8180
  selector:
    app: prometheus
    component: server
